global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "offbook"
    static_configs:
      - targets: ["app:3000"]
    metrics_path: "/api/metrics"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
